export const LANGUAGE_CODES = Object.freeze({
  en: 'EN',
  es: 'ES'
});

export const SUPPORTED_LANGUAGES = Object.freeze(Object.keys(LANGUAGE_CODES));

export const DICTIONARY = {
  en: {
    pageTitle: 'Gabriel Professional Business Services',
    pageDescription: 'Business services for logistics, IT, admin, and customer relations.',
    switchToEnglish: 'Switch language to English',
    switchToSpanish: 'Switch language to Spanish',
    home: 'Home',
    services: 'Services',
    about: 'About',
    pricing: 'Pricing',
    contact: 'Contact',
    careers: 'Careers',
    brandSubtitle: 'Outsource, Delivered',
    editorialTheme: 'Wall Street News Cut',
    heroTitle: 'Professional services for logistics, IT, and customer operations.',
    heroBody: 'Scale support with expert teams, measurable SLAs, and human-centered delivery.',
    startTrial: 'Start Free Trial',
    schedule: 'Schedule Consultation',
    aboutBody: 'Gabriel Services provides multilingual operational support designed for modern digital businesses.',
    name: 'Name',
    email: 'Email',
    contactNumber: 'Your Contact Number',
    countryCode: 'Country code',
    countryCodePlaceholder: 'Select country code',
    contactTime: 'Most convenient time to contact you',
    message: 'Message',
    send: 'Send',
    sent: 'Message captured. We will contact you shortly.',
    blocked: 'Submission blocked by security checks. Please remove code-like content and retry.',
    contactIntro: 'Reach our team for support, onboarding, or partnership requests.',
    serviceLearnMore: 'Learn more',
    serviceLabel: 'Service',
    serviceCarouselToggles: 'Service carousel toggles',
    serviceShowPrefix: 'Show',
    serviceCardAction: 'View service details',
    serviceLogisticsTitle: 'Logistics Operations',
    serviceLogisticsBody: 'Order workflows, dispatch support, shipment updates, and reporting.',
    serviceItTitle: 'IT Support',
    serviceItBody: 'Tier 1, Tier 2; On-boarding, implementation, troubleshooting, account management, customer relations, and endpoint support.',
    serviceAdminTitle: 'Administrative Backoffice',
    serviceAdminBody: 'Data entry, documentation, invoicing support, accounts payable and receivable, process management, scheduling, and executive assistant services.',
    serviceCustomerTitle: 'Customer Relations',
    serviceCustomerBody: 'Omnichannel support, customer retention, and quality monitoring.',
    careersTitle: 'Careers',
    careersIntro: 'Join our team and help SMB clients modernize logistics, IT, and support operations.',
    experience: 'Experience',
    education: 'Education',
    certification: 'Certification',
    skills: 'Skills',
    expertise: 'Current Level of Expertise',
    languages: 'Languages',
    controls: 'controls',
    add: '+ Add',
    remove: '- Remove',
    lockSection: 'Lock section',
    unlockSection: 'Unlock section',
    submitApplication: 'Submit Application',
    selectLevel: 'Select level',
    entry: 'Entry',
    junior: 'Junior',
    mid: 'Mid',
    advanced: 'Advanced',
    expert: 'Expert',
    placeholderExperience: 'Describe your experience',
    placeholderEducation: 'Share your education background',
    placeholderCertification: 'List your certifications',
    placeholderSkills: 'Add your skills',
    placeholderExpertise: 'Describe your expertise',
    placeholderLanguages: 'List language(s) and level',
    placeholderContactNumber: '555 123 4567',
    fabOpenQuickActions: 'Open quick actions',
    fabContact: 'Contact',
    fabCareer: 'Career',
    fabChatbot: 'Chatbot',
    chatPanelLabel: 'Chatbot panel',
    chatClose: 'Close chatbot',
    chatbot: 'Chatbot',
    footerCopyright: 'Gabriel Professional Business Services'
  },
  es: {
    pageTitle: 'Gabriel Servicios Profesionales Empresariales',
    pageDescription: 'Servicios empresariales de logística, TI, administración y atención al cliente.',
    switchToEnglish: 'Cambiar idioma a inglés',
    switchToSpanish: 'Cambiar idioma a español',
    home: 'Inicio',
    services: 'Servicios',
    about: 'Nosotros',
    pricing: 'Precios',
    contact: 'Contacto',
    careers: 'Carreras',
    brandSubtitle: 'Tercerización que entrega',
    editorialTheme: 'Recorte informativo de Wall Street',
    heroTitle: 'Servicios profesionales para logística, TI y operaciones de atención al cliente.',
    heroBody: 'Escale su soporte con equipos expertos, SLA medibles y una entrega centrada en las personas.',
    startTrial: 'Iniciar prueba gratuita',
    schedule: 'Programar consulta',
    aboutBody: 'Gabriel Services ofrece soporte operativo multilingüe diseñado para negocios digitales modernos.',
    name: 'Nombre',
    email: 'Correo electrónico',
    contactNumber: 'Su número de contacto',
    countryCode: 'Código de país',
    countryCodePlaceholder: 'Seleccione código de país',
    contactTime: 'Hora más conveniente para contactarle',
    message: 'Mensaje',
    send: 'Enviar',
    sent: 'Mensaje recibido. Nos pondremos en contacto pronto.',
    blocked: 'Contenido bloqueado por seguridad. Elimine contenido sospechoso e inténtelo de nuevo.',
    contactIntro: 'Contacte a nuestro equipo para soporte, incorporación o alianzas.',
    serviceLearnMore: 'Más información',
    serviceLabel: 'Servicio',
    serviceCarouselToggles: 'Controles del carrusel de servicios',
    serviceShowPrefix: 'Mostrar',
    serviceCardAction: 'Ver detalles del servicio',
    serviceLogisticsTitle: 'Operaciones Logísticas',
    serviceLogisticsBody: 'Flujos de pedidos, soporte de despacho, actualizaciones de envíos y reportes.',
    serviceItTitle: 'Soporte de TI',
    serviceItBody: 'Nivel 1 y 2; incorporación, implementación, solución de problemas, gestión de cuentas, relaciones con clientes y soporte de terminales.',
    serviceAdminTitle: 'Backoffice Administrativo',
    serviceAdminBody: 'Ingreso de datos, documentación, apoyo de facturación, cuentas por pagar y cobrar, gestión de procesos, agenda y asistencia ejecutiva.',
    serviceCustomerTitle: 'Relaciones con Clientes',
    serviceCustomerBody: 'Soporte omnicanal, retención de clientes y monitoreo de calidad.',
    careersTitle: 'Carreras',
    careersIntro: 'Únase a nuestro equipo y ayude a clientes PyME a modernizar logística, TI y operaciones de soporte.',
    experience: 'Experiencia',
    education: 'Educación',
    certification: 'Certificación',
    skills: 'Habilidades',
    expertise: 'Nivel actual de experiencia',
    languages: 'Idiomas',
    controls: 'controles',
    add: '+ Agregar',
    remove: '- Quitar',
    lockSection: 'Bloquear sección',
    unlockSection: 'Desbloquear sección',
    submitApplication: 'Enviar solicitud',
    selectLevel: 'Seleccione nivel',
    entry: 'Inicial',
    junior: 'Junior',
    mid: 'Intermedio',
    advanced: 'Avanzado',
    expert: 'Experto',
    placeholderExperience: 'Describa su experiencia',
    placeholderEducation: 'Comparta su formación académica',
    placeholderCertification: 'Liste sus certificaciones',
    placeholderSkills: 'Agregue sus habilidades',
    placeholderExpertise: 'Describa su nivel de experiencia',
    placeholderLanguages: 'Indique idioma(s) y nivel',
    placeholderContactNumber: '555 123 4567',
    fabOpenQuickActions: 'Abrir acciones rápidas',
    fabContact: 'Contacto',
    fabCareer: 'Carrera',
    fabChatbot: 'Chatbot',
    chatPanelLabel: 'Panel del chatbot',
    chatClose: 'Cerrar chatbot',
    chatbot: 'Chatbot',
    footerCopyright: 'Gabriel Servicios Profesionales Empresariales'
  }
};

export const SERVICES = {
  en: [
    { key: 'logistics', title: 'Logistics Operations', body: 'Order workflows, dispatch support, shipment updates, and reporting.', href: '/services/logistics-operations/' },
    { key: 'it', title: 'IT Support', body: 'Tier 1, Tier 2; On-boarding, implementation, troubleshooting, account management, customer relations, and endpoint support.', href: '/services/it-support/' },
    { key: 'admin', title: 'Administrative Backoffice', body: 'Data entry, documentation, invoicing support, accounts payable and receivable, process management, scheduling, and executive assistant services.', href: '/services/administrative-backoffice/' },
    { key: 'customer', title: 'Customer Relations', body: 'Omnichannel support, customer retention, and quality monitoring.', href: '/services/customer-relations/' }
  ],
  es: [
    { key: 'logistics', title: 'Operaciones Logísticas', body: 'Flujos de pedidos, soporte de despacho, actualizaciones de envíos y reportes.', href: '/services/logistics-operations/' },
    { key: 'it', title: 'Soporte de TI', body: 'Nivel 1 y 2; incorporación, implementación, solución de problemas, gestión de cuentas, relaciones con clientes y soporte de terminales.', href: '/services/it-support/' },
    { key: 'admin', title: 'Backoffice Administrativo', body: 'Ingreso de datos, documentación, apoyo de facturación, cuentas por pagar y cobrar, gestión de procesos, agenda y asistencia ejecutiva.', href: '/services/administrative-backoffice/' },
    { key: 'customer', title: 'Relaciones con Clientes', body: 'Soporte omnicanal, retención de clientes y monitoreo de calidad.', href: '/services/customer-relations/' }
  ]
};

export const PLANS = {
  en: [
    { name: 'Individual', price: '$3,950/mo', points: ['Email support', 'Business hours', 'Monthly report'] },
    { name: 'Small Business', price: '$4,850/mo', points: ['24/7 support', 'Priority SLA', 'Weekly optimization'] },
    { name: 'Medium Business', price: '$5,950/mo', points: ['Dedicated team', 'Custom integrations', 'Compliance alignment'] }
  ],
  es: [
    { name: 'Individual', price: '$3,950 usd/mes', points: ['Soporte por correo', 'Horario laboral', 'Reporte mensual'] },
    { name: 'Pequeña Empresa', price: '$4,850 usd/mes', points: ['Soporte 24/7', 'SLA prioritario', 'Optimización semanal'] },
    { name: 'Mediana Empresa', price: '$5,950 usd/mes', points: ['Equipo dedicado', 'Integraciones a medida', 'Alineación de cumplimiento'] }
  ]
};
