export const LANGUAGE_CODES = Object.freeze({
  en: 'EN',
  es: 'ES'
});

export const SUPPORTED_LANGUAGES = Object.freeze(Object.keys(LANGUAGE_CODES));

export const DICTIONARY = {
  en: {
    pageTitle: 'Gabriel Services',
    pageTitleHome: 'Gabriel Services | Home',
    pageTitleAbout: 'Gabriel Services | About',
    pageTitleServices: 'Gabriel Services | Services',
    pageTitlePricing: 'Gabriel Services | Pricing',
    pageTitleCareers: 'Gabriel Services | Careers',
    pageTitleContact: 'Gabriel Services | Contact',
    pageTitleServiceLogistics: 'Gabriel Services | Logistics Operations',
    pageTitleServiceAdmin: 'Gabriel Services | Administrative Backoffice',
    pageTitleServiceCustomer: 'Gabriel Services | Customer Relations',
    pageTitleServiceIt: 'Gabriel Services | IT Support',
    pageTitleLearning: 'Gabriel Services | Learning',
    pageDescription: 'Business services for logistics, IT, admin, and customer relations.',
    pageDescriptionHome: 'Business services for logistics, IT, admin, and customer relations.',
    pageDescriptionAbout: 'Learn how Gabriel Services supports growing businesses through logistics, administration, customer operations, and IT execution.',
    pageDescriptionServices: 'Explore logistics, administrative backoffice, customer relations, and IT support services from Gabriel Services.',
    pageDescriptionPricing: 'Understand Gabriel Services pricing models based on scope, complexity, and operational support needs.',
    pageDescriptionCareers: 'Apply to join Gabriel Services and support modern logistics, IT, and customer operations for SMB clients.',
    pageDescriptionContact: 'Contact Gabriel Services for onboarding, operational support, and partnership inquiries.',
    pageDescriptionLearning: 'Practical learning resources for operations, service quality, logistics coordination, and administrative workflows.',
    pageDescriptionServiceLogistics: 'Logistics operations support for dispatch coordination, shipment tracking, and execution follow-up.',
    pageDescriptionServiceAdmin: 'Administrative backoffice support for documentation, scheduling, reporting, and process continuity.',
    pageDescriptionServiceCustomer: 'Customer relations support for communication rhythm, case handling, and service continuity.',
    pageDescriptionServiceIt: 'IT support services for ticket triage, troubleshooting coordination, and day-to-day technical continuity.',
    switchToEnglish: 'Switch language to English',
    switchToSpanish: 'Switch language to Spanish',
    languageSelector: 'Language selector',
    ogLocale: 'en_US',
    home: 'Home',
    services: 'Services',
    about: 'About',
    pricing: 'Pricing',
    pricingFeaturesLabel: 'Features',

    pricingHeroTitle: 'Pricing',
    pricingHeroLead: 'Pricing is structured around business needs, workflow complexity, coverage level, and the operational volume involved.',
    pricingHowTitle: 'How pricing works',
    pricingHowBody: 'Pricing depends on service scope, coordination depth, support hours, communication rhythm, and the reporting requirements your team expects across daily operations.',
    pricingEngagementTitle: 'Engagement options',
    pricingOptionOngoingTitle: 'Ongoing support',
    pricingOptionOngoingBody: 'For teams that require steady day-to-day operational continuity.',
    pricingOptionSharedTitle: 'Shared support coverage',
    pricingOptionSharedBody: 'For organizations balancing multiple workflows with flexible priorities.',
    pricingOptionProjectTitle: 'Project-based support',
    pricingOptionProjectBody: 'For short-term execution with defined scope, timeline, and deliverables.',
    pricingFactorsTitle: 'What affects pricing',
    pricingFactorsBody: 'Final pricing is influenced by workflow complexity, business volume, required support hours, communication requirements, and any system or process requirements involved in day-to-day delivery.',
    pricingTailoredTitle: 'Request a tailored scope',
    pricingTailoredBody: 'Tell us what your team needs, and we will prepare a consultation-focused scope aligned to your operational goals.',
    pricingTailoredPrimaryCta: 'Request a consultation',
    pricingTailoredSecondaryCta: 'Describe your needs',
    contactHeroTitle: 'Contact Gabriel Services',
    contactHeroLead: 'Reach our team for support, onboarding, project discussions, or partnership inquiries.',
    contactReachTitle: 'How to reach us',
    contactReachBody: 'This contact channel is designed for businesses that need operational support, service onboarding guidance, or partnership conversations with Gabriel Services.',
    contactTellTitle: 'Tell us what you need',
    contactTellBody: 'Share your current workflows, priorities, and expected response needs so we can route your request accurately.',
    contactNextTitle: 'What happens next',
    contactNextBody: 'Our team reviews submissions, confirms scope details when needed, and follows up with recommended next steps and expected onboarding flow.',
    contact: 'Contact',
    careers: 'Careers',
    learning: 'Learning',
    learningIntro1: 'Explore practical ideas and guides focused on daily business operations, customer support consistency, logistics coordination, and administrative workflows.',
    learningIntro2: 'This section is designed to help teams stay aligned, improve execution quality, and build reliable systems that support sustainable growth.',
    brandSubtitle: 'Tercerización que entrega',
    editorialTheme: 'Corte estilo revista',
    homeHeroTitle: 'Professional services for logistics, IT, and customer operations.',
    homeHeroLead: 'Scale your operation with expert teams, measurable service levels, and precision execution across logistics, IT, and customer operations.',
    homeHeroPrimaryCta: 'Schedule consultation',
    homeHeroSecondaryCta: 'Explore services',
    homeHeroSupportText: 'Execution-oriented teams aligned with your daily workflows, communication rhythm, and measurable outcomes.',
    homeOpsTitle: 'Operational support for modern businesses',
    homeOpsBody1: 'Gabriel Services is a professional support partner for organizations that need reliable execution in logistics, administrative coordination, customer operations, and IT requests.',
    homeOpsBody2: 'We provide structured coverage, clear communication, measurable follow-up, and process discipline that keeps operations moving without disruption.',
    homeOpsBody3: 'Our teams integrate with existing systems and operating rhythms, creating a practical execution layer that helps leaders reduce friction, improve response quality, and stay focused on growth priorities.',
    homeServiceAreasTitle: 'Service areas designed for day-to-day execution',
    homeCardLogisticsTitle: 'Logistics operations',
    homeCardLogisticsBody: 'Dispatch coordination, movement tracking, and delivery workflow support with reliable updates.',
    homeCardAdminTitle: 'Administrative backoffice',
    homeCardAdminBody: 'Documentation, scheduling, data management, and process administration to keep business systems organized.',
    homeCardCustomerTitle: 'Customer operations',
    homeCardCustomerBody: 'Client communication, issue handling, and continuity support designed for agile and consistent service experiences.',
    homeCardItTitle: 'IT support',
    homeCardItBody: 'Technical request triage, troubleshooting coordination, and practical support for day-to-day platforms.',
    homeWhyTitle: 'Why companies work with Gabriel Services',
    homeWhyBody: 'Companies choose Gabriel Services for reliability under daily pressure, clear and accountable communication, structure that reduces operational drift, and adaptive support that scales as priorities evolve.',
    homeStartTitle: 'Start with the support you need',
    homeStartBody: 'Schedule a consultation to map workflows, define service coverage, and build an execution plan tailored to your operational needs.',
    homeStartPrimaryCta: 'Request consultation',
    homeStartSecondaryCta: 'View hiring options',
    heroTitle: 'Professional services for logistics, IT, and customer operations.',
    heroBody: 'Scale support with expert teams, measurable SLAs, and precision-driven delivery.',
    schedule: 'Schedule Consultation',
    aboutBody: 'Gabriel Services provides multilingual operational support designed for modern digital businesses.',
    aboutBodyP1: 'At Gabriel Services, we understand that business success depends on efficient teams, clear communication, and reliable day-to-day operations.',
    aboutBodyP2: 'Our background as former small business owners and remote business support professionals, combined with experience across customer service, logistics, tech support, administration, and business operations, has taught us that small details can quickly turn into costly problems when they are not handled consistently.',
    aboutBodyP3: 'That is why we help businesses stay organized, responsive, and operationally strong. We bring practical experience, adaptability, and a customer-focused mindset to the everyday challenges companies face, delivering support that is efficient, cost-conscious, and dependable.',
    aboutBodyP4: 'Our purpose is to strengthen daily operations so business owners can focus on planning, leading, and growing with greater confidence.',

    aboutHeroTitle: 'About Gabriel Services',
    aboutHeroLead: 'Gabriel Services helps businesses stay organized, responsive, and operationally strong through practical support across logistics, administration, customer operations, and IT.',
    aboutWhoTitle: 'Who we are',
    aboutWhoBody: 'Gabriel Services was built to give growing companies a dependable operational partner that understands the pace and pressure of daily business execution.',
    aboutBringTitle: 'What we bring to daily operations',
    aboutBringBody1: 'Our team brings direct experience in customer service, logistics coordination, administrative back-office support, IT triage, and day-to-day business operations.',
    aboutBringBody2: 'This cross-functional foundation helps us support workflows end-to-end instead of treating each request as an isolated task.',
    aboutSupportTitle: 'How we support growing businesses',
    aboutSupportBody: 'As companies scale, small unmanaged details can quickly become expensive operational issues. We reduce that risk through consistent execution, transparent communication, and disciplined follow-up across recurring workflows.',
    aboutApproachTitle: 'Our operating approach',
    aboutApproachBody: 'Our approach is built on reliability, steady communication rhythm, practical execution, and cost-conscious service delivery so businesses can maintain momentum with confidence.',
    aboutApproachPrimaryCta: 'Explore services',
    aboutApproachSecondaryCta: 'Schedule a consultation',
    servicesHeroTitle: 'Services',
    servicesHeroLead: 'Gabriel Services provides flexible operational support across logistics, administrative back office, customer operations, and IT support.',
    servicesHeroCta: 'Discuss your workflow',
    servicesCoverageTitle: 'Professional support across key business functions',
    servicesMatrixTitle: 'Service matrix',
    servicesMatrixLead: 'A quick view to understand how each service line supports execution priorities.',
    servicesMatrixAriaLabel: 'Service capabilities matrix',
    servicesMatrixHeaderFunction: 'Function',
    servicesMatrixHeaderLogistics: 'Logistics',
    servicesMatrixHeaderCustomerOps: 'Customer operations',
    servicesMatrixHeaderAdmin: 'Administrative back office',
    servicesMatrixHeaderIt: 'IT support',
    servicesMatrixRowOperational: 'Operational support',
    servicesMatrixRowCadence: 'Follow-up cadence',
    servicesMatrixRowDocs: 'Documentation',
    servicesMatrixRowCoordination: 'Coordination',
    servicesMatrixRowClientContinuity: 'Customer continuity',
    servicesMatrixRowDispatch: 'Dispatch support',
    servicesMatrixRowScheduling: 'Scheduling',
    servicesMatrixRowReporting: 'Reporting',
    servicesEngagementTitle: 'Engagement options',
    servicesEngagementOnDemandTitle: 'On demand',
    servicesEngagementOnDemandBody: 'Ideal for variable needs, workload spikes, and last-minute requests.',
    servicesEngagementOnDemandItem1: 'Hourly',
    servicesEngagementOnDemandItem2: '4-hour block',
    servicesEngagementOnDemandItem3: '8-hour block',
    servicesEngagementContinuousTitle: 'Continuous coverage',
    servicesEngagementContinuousBody: 'Ideal for recurring tasks and constant operational continuity.',
    servicesEngagementContinuousItem1: 'Part time',
    servicesEngagementContinuousItem2: 'Full time',
    servicesEngagementContinuousItem3: 'Daily',
    servicesEngagementContinuousItem4: 'Weekly',
    servicesEngagementContinuousItem5: 'Monthly',
    servicesEngagementProjectTitle: 'Project based',
    servicesEngagementProjectBody: 'Ideal for defined scopes and focused execution.',
    servicesEngagementProjectItem1: 'By project',
    servicesEngagementProjectItem2: 'Short term',
    servicesEngagementProjectItem3: 'Milestone based',
    servicesEngagementCta: 'Schedule consultation',
    servicesExecutionTitle: 'How we support execution',
    servicesExecutionItem1: 'Structured support',
    servicesExecutionItem2: 'Multilingual communication',
    servicesExecutionItem3: 'Steady follow-up',
    servicesExecutionItem4: 'Practical, cost-conscious operations',
    servicesExecutionPrimaryCta: 'Request support',
    servicesExecutionSecondaryCta: 'View engagement options',
    name: 'Name',
    email: 'Email',
    contactNumber: 'Your Contact Number',
    countryCode: 'Country code',
    phoneNumber: 'Phone number',
    countryCodePlaceholder: 'Select country code',
    contactTime: 'Most convenient time to contact you',
    message: 'Message',
    send: 'Send',
    sent: 'Message captured. We will contact you shortly.',
    blocked: 'Submission blocked by security checks. Please remove code-like content and retry.',
    review: 'Submission captured with caution. Please avoid HTML/JS snippets unless required.',
    contactIntro: 'Reach our team for support, onboarding, or partnership requests.',
    learnMore: 'Learn more',
    serviceLearnMore: 'Learn more',
    serviceCardExploreLink: 'Explore service',
    serviceLabel: 'Service',
    serviceCarouselToggles: 'Service carousel toggles',
    serviceShowPrefix: 'Show',
    serviceCardAction: 'View service details',
    serviceLogisticsTitle: 'Logistics Operations',
    serviceLogisticsBody: 'Order workflows, dispatch support, shipment updates, and reporting.',
    serviceItTitle: 'IT Support',
    serviceItBody: 'Tier 1 and Tier 2 onboarding, implementation, troubleshooting, account management, customer relations, and endpoint support.',
    serviceAdminTitle: 'Administrative Backoffice',
    serviceAdminBody: 'Data entry, documentation, invoicing support, accounts payable and receivable, process management, scheduling, and executive assistant services.',
    serviceCustomerTitle: 'Customer Relations',
    serviceCustomerBody: 'Omnichannel support, customer retention, and quality monitoring.',
    serviceDefinitionsTitle: 'Service Definitions',
    serviceDefinitionOperationsTitle: 'Operations',
    serviceDefinitionOperationsBody: 'Operations is the end-to-end execution system that designs, controls, and continuously improves how people, processes, and technology convert inputs into consistent, high-quality outputs—delivering predictable performance across cost, risk, and customer outcomes under real-world constraints.',
    serviceDefinitionLogisticsTitle: 'Logistics',
    serviceDefinitionLogisticsBody: 'Logistics is the end-to-end system that plans, executes, and continuously optimizes transportation, storage, inventory movement, and visibility to move items through a network from origin to destination—delivering on-time, accurate, in-good-condition fulfillment while managing total cost, capacity, risk, and customer experience.',
    serviceDefinitionRemoteVirtualAssistanceTitle: 'Remote virtual assistance',
    serviceDefinitionRemoteVirtualAssistanceBody: 'Remote virtual assistance is an on-demand, remote workforce capability that uses standardized digital workflows and tools to offload administrative, customer, and operational tasks—improving speed, accuracy, service quality, and cost efficiency through measurable outcomes.',
    serviceDefinitionTechConsultantLevelITitle: 'Tech Consultant Level I',
    serviceDefinitionTechConsultantLevelIBody: 'Tech Consultant Level I is a delivery support role that executes well-defined technical tasks to stabilize systems and hit project milestones using standard playbooks, measuring results and escalating complexity when needed, under senior guidance.',
    serviceDefinitionTechConsultantLevelIITitle: 'Tech Consultant Level II',
    serviceDefinitionTechConsultantLevelIIBody: 'Tech Consultant Level II is an independent delivery owner who translates client needs into implemented solutions—leading scoped work end-to-end to improve reliability, security, and cost performance, while coordinating stakeholders and mentoring junior staff.',
    serviceDefinitionRemoteAdministrativeBackOfficeTitle: 'Remote administrative back office',
    serviceDefinitionRemoteAdministrativeBackOfficeBody: 'Remote administrative back office is a scalable, offsite capability that standardizes and runs core internal admin workflows—documentation, data management, coordination, reporting, and routine controls—so the business operates with higher accuracy, faster cycle times, and lower cost and risk.',

    serviceDetailDescriptionTitle: 'Service description',
    serviceDetailCoverageTitle: 'What this service covers',
    serviceDetailWorkflowsTitle: 'Common workflows',
    serviceDetailResultsTitle: 'Operational outcomes',
    serviceDetailCollaborationTitle: 'How collaboration works',
    serviceDetailRelatedTitle: 'Related services',
    serviceLogisticsDetailTitle: 'Logistics Operations',
    serviceLogisticsDetailLead: 'Logistics Operations provides reliable execution coverage for daily high-coordination workflows. We help manage communication, follow-up, and documentation across multiple fronts to keep operations organized, visible, and on track.',
    serviceLogisticsDetailDescriptionBody: 'This service is designed for businesses that need reliable coordination in active logistics operations. We help maintain communication flow, improve follow-up, and strengthen alignment on the daily tasks that sustain logistics activity.',
    serviceLogisticsCoverage1: 'Coordination',
    serviceLogisticsCoverage2: 'Dispatch',
    serviceLogisticsCoverage3: 'Delivery follow-up',
    serviceLogisticsCoverage4: 'Escalation',
    serviceLogisticsCoverage5: 'Communications',
    serviceLogisticsCoverage6: 'Documentation',
    serviceLogisticsWorkflow1: 'Tracking',
    serviceLogisticsWorkflow2: 'Escalation',
    serviceLogisticsWorkflow3: 'Communication and follow-up',
    serviceLogisticsResult1: 'Fewer communication gaps',
    serviceLogisticsResult2: 'Greater delivery visibility',
    serviceLogisticsResult3: 'More consistent operational follow-up',
    serviceLogisticsResult4: 'Stronger day-to-day execution',
    serviceLogisticsDetailCollaborationBody: 'We start by reviewing your workflow, operational priorities, and communication requirements. Then we align execution with your process to manage logistics tasks with clearer coordination, better updates, and more reliable follow-up.',
    serviceAdminDetailTitle: 'Administrative Back Office',
    serviceAdminDetailLead: 'Administrative back office provides structured coverage for recurring administrative tasks that keep business operations stable. We manage documentation, internal coordination, and follow-up to sustain organized and consistent processes.',
    serviceAdminDetailDescriptionBody: 'This service is designed for businesses that require reliable coverage for routine administrative operations. We help reduce task accumulation, maintain internal order, and sustain recurring workflows with greater consistency and clarity.',
    serviceAdminCoverage1: 'Documentation',
    serviceAdminCoverage2: 'Scheduling',
    serviceAdminCoverage3: 'Reporting',
    serviceAdminCoverage4: 'Operational follow-up',
    serviceAdminCoverage5: 'Internal coordination',
    serviceAdminCoverage6: 'Administrative continuity',
    serviceAdminWorkflow1: 'Document preparation and organization',
    serviceAdminWorkflow2: 'Record maintenance',
    serviceAdminWorkflow3: 'Internal request management',
    serviceAdminWorkflow4: 'Scheduling and coordination',
    serviceAdminWorkflow5: 'Recurring administrative follow-up',
    serviceAdminResult1: 'Stronger operational organization',
    serviceAdminResult2: 'Lower administrative backlog',
    serviceAdminResult3: 'Better internal continuity',
    serviceAdminResult4: 'More consistent day-to-day execution',
    serviceAdminDetailCollaborationBody: 'We begin by reviewing your workflow, recurring priorities, and communication rhythm. Then we align execution with your internal process so administrative tasks are recorded, organized, and followed through with greater consistency and control.',
    serviceCustomerDetailTitle: 'Customer Relations',
    serviceCustomerDetailLead: 'Customer relations provides operational support for communication and follow-up throughout the service lifecycle. We help maintain clear responses, case continuity, and stable coordination in daily customer interactions.',
    serviceCustomerDetailDescriptionBody: 'This service is designed for businesses that need consistent support in customer-facing communication and follow-up. We help maintain response continuity, improve service coordination, and strengthen visibility over ongoing interactions.',
    serviceCustomerCoverage1: 'Customer support',
    serviceCustomerCoverage2: 'Issue management',
    serviceCustomerCoverage3: 'Continuity communication',
    serviceCustomerCoverage4: 'Post-sales communication',
    serviceCustomerCoverage5: 'Follow-up and escalation',
    serviceCustomerWorkflow1: 'Responding to customer requests',
    serviceCustomerWorkflow2: 'Status and case updates',
    serviceCustomerWorkflow3: 'Follow-up coordination',
    serviceCustomerResult1: 'More consistent customer communication',
    serviceCustomerResult2: 'Stronger customer experience',
    serviceCustomerResult3: 'Fewer missed or delayed follow-ups',
    serviceCustomerResult4: 'Better continuity in customer interactions',
    serviceCustomerDetailCollaborationBody: 'We start by reviewing your communication flow, response priorities, and follow-up expectations. Then we align execution with your process to manage customer interactions with greater consistency, visibility, and operational clarity.',
    serviceItDetailTitle: 'IT Support',
    serviceItDetailLead: 'IT support provides reliable coverage for day-to-day internal technical needs. We help organize request intake, maintain visibility over open incidents, and sustain clear communication throughout the process.',
    serviceItDetailDescriptionBody: 'This service is designed for businesses that need structured daily coverage for common internal technical requests. We help keep ticket flow organized, sustain communication continuity, and improve follow-up so routine technical operations remain stable and well coordinated.',
    serviceItCoverage1: 'Help desk',
    serviceItCoverage2: 'Ticket management',
    serviceItCoverage3: 'User coordination and follow-up',
    serviceItCoverage4: 'Troubleshooting',
    serviceItCoverage5: 'Communication',
    serviceItWorkflow1: 'Ticket and documentation management',
    serviceItWorkflow2: 'Triage',
    serviceItWorkflow3: 'Request follow-up and coordination',
    serviceItResult1: 'More reliable operational flow',
    serviceItResult2: 'Greater visibility over open requests',
    serviceItResult3: 'Clearer follow-up and coordination',
    serviceItResult4: 'Less friction in routine technical activity',
    serviceItDetailCollaborationBody: 'We begin by reviewing your workflow, request priorities, and communication needs. Then we align execution with your internal process so routine technical requests are handled with clear follow-up, stronger visibility, and consistent coordination.',
    careersTitle: 'Careers',
    careersIntro: 'Join our team and help SMB clients modernize logistics, IT, and support operations.',
    careersHeroTitle: 'Careers at Gabriel Services',
    
    careersHeroLead: 'Join a team that helps businesses strengthen logistics, IT, admin, and customer operations with practical, reliable execution.',
    careersWhyTitle: 'Why join Gabriel Services',
    careersWhyBody: 'Our work centers on high-accountability operational support. Every team member is expected to communicate clearly, execute consistently, and deliver practical solutions under real business pressure.',
    careersFormTitle: 'Application form',
    careersFormBody: 'Share clear and relevant details so our recruitment and operations team can assess your profile accurately.',
    careersSkillsTitle: 'Skills, experience, and background',
    careersSkillsBody: 'Applicants can include previous experience, academic background, certifications, key skills, current specialization level, and language capabilities relevant to operational support roles.',
    careersNextTitle: 'What happens after you apply',
    careersNextBody: 'After review, shortlisted candidates are contacted for next steps, role alignment, and interview scheduling based on current hiring priorities.',
    experience: 'Experience',
    education: 'Education',
    certification: 'Certification',
    skills: 'Skills',
    expertise: 'Current Level of Expertise',
    languages: 'Languages',
    controls: 'controls',
    add: '+ Add',
    remove: '- Remove',
    lockSection: 'Lock section',
    unlockSection: 'Unlock section',
    submitApplication: 'Submit Application',
    selectLevel: 'Select level',
    entry: 'Entry',
    junior: 'Junior',
    mid: 'Mid',
    advanced: 'Advanced',
    expert: 'Expert',
    placeholderExperience: 'Describe your experience',
    placeholderEducation: 'Share your education background',
    placeholderCertification: 'List your certifications',
    placeholderSkills: 'Add your skills',
    placeholderExpertise: 'Describe your expertise',
    placeholderLanguages: 'List language(s) and level',
    placeholderContactNumber: '555 123 4567',
    fabOpenQuickActions: 'Open quick actions',
    fabContact: 'Contact',
    fabCareer: 'Careers',
    fabChatbot: 'Chatbot',
    chatPanelLabel: 'Chatbot panel',
    chatClose: 'Close chatbot',
    chatCloseCta: 'Close',
    chatbot: 'Gabo io',
    chatFrameTitle: 'Chat assistant',
    legalNavigation: 'Legal navigation',
    legalTerms: 'Terms and Conditions',
    legalCookies: 'Cookie Consent',
    legalPrivacy: 'Privacy and GDPR',
    footerCompany: 'Company',
    footerSupport: 'Support',
    footerLegal: 'Legal',
    footerSitemap: 'Sitemap',
    footerTerms: 'T&C',
    footerCookies: 'Cookies Consent',
    footerGdpr: 'Privacy and GDPR',
    footerCopyright: 'Gabriel Services',
    opsHeading: 'Integrated delivery framework',
    opsIntro: 'A synchronized model that connects secure delivery, adaptive UX, governance, and observability in one operating rhythm.',
    opsLifecycleTitle: 'Intelligent code lifecycle',
    opsLifecycleBody: 'Coordinate CI/CD, cloud-native automation, and plain-language documentation across the full release path.',
    opsDesignTitle: 'Adaptive UX/UI intelligence',
    opsDesignBody: 'Ship human-centered interfaces with responsive layouts, accessibility, and measurable interaction quality.',
    opsSecurityTitle: 'Security + compliance orchestration',
    opsSecurityBody: 'Align NIST CSF, CISA Cyber Essentials, and PCI controls from identify to recover across operations.',
    opsGovernanceTitle: 'Web governance controls',
    opsGovernanceBody: 'Reinforce governance with secure headers, privacy standards, and policy-aware platform configuration.',
    opsAiTitle: 'AI/ML/LLM integration',
    opsAiBody: 'Connect assistants and tiny models for real-time personalization while preserving security and budget efficiency.',
    opsDataTitle: 'Observability and analytics loops',
    opsDataBody: 'Monitor Core Web Vitals, service health, and behavior data to continuously optimize UX, resilience, and outcomes.'
  },
  es: {
    pageTitle: 'Gabriel Servicios Profesionales para PYMEs',
    pageTitleHome: 'Gabriel Services | Inicio',
    pageTitleAbout: 'Gabriel Services | Nosotros',
    pageTitleServices: 'Gabriel Services | Servicios',
    pageTitlePricing: 'Gabriel Services | Precios',
    pageTitleCareers: 'Gabriel Services | Carreras',
    pageTitleContact: 'Gabriel Services | Contacto',
    pageTitleServiceLogistics: 'Gabriel Services | Operaciones logísticas',
    pageTitleServiceAdmin: 'Gabriel Services | Back office administrativo',
    pageTitleServiceCustomer: 'Gabriel Services | Relación con clientes',
    pageTitleServiceIt: 'Gabriel Services | Soporte de TI',
    pageTitleLearning: 'Gabriel Services | Aprendizaje',
    pageDescription: 'Servicios empresariales de logística, TI, administración y atención al cliente.',
    pageDescriptionHome: 'Servicios empresariales de logística, TI, administración y atención al cliente.',
    pageDescriptionAbout: 'Conozca cómo Gabriel Services impulsa empresas en crecimiento con ejecución en logística, administración, operaciones de clientes y TI.',
    pageDescriptionServices: 'Explore los servicios de logística, back office administrativo, relaciones con clientes y soporte de TI de Gabriel Services.',
    pageDescriptionPricing: 'Conozca los modelos de precios de Gabriel Services según alcance, complejidad y necesidades operativas.',
    pageDescriptionCareers: 'Postúlese para unirse a Gabriel Services y apoyar operaciones modernas de logística, TI y atención al cliente para pymes.',
    pageDescriptionContact: 'Contacte a Gabriel Services para incorporación, soporte operativo y alianzas estratégicas.',
    pageDescriptionLearning: 'Recursos prácticos de aprendizaje para operaciones, calidad de servicio, coordinación logística y flujos administrativos.',
    pageDescriptionServiceLogistics: 'Soporte de operaciones logísticas para coordinación de despachos, seguimiento de envíos y continuidad de ejecución.',
    pageDescriptionServiceAdmin: 'Soporte de back office administrativo para documentación, agenda, reportes y continuidad de procesos.',
    pageDescriptionServiceCustomer: 'Soporte de relaciones con clientes para comunicación, gestión de casos y continuidad del servicio.',
    pageDescriptionServiceIt: 'Servicios de soporte TI para triage de tickets, coordinación de incidencias y continuidad técnica diaria.',
    switchToEnglish: 'Cambiar idioma a inglés',
    switchToSpanish: 'Cambiar idioma a español',
    languageSelector: 'Selector de idioma',
    ogLocale: 'es_ES',
    home: 'Inicio',
    services: 'Servicios',
    about: 'Nosotros',
    pricing: 'Precios',
    pricingFeaturesLabel: 'Características',

    pricingHeroTitle: 'Precios',
    pricingHeroLead: 'Los precios se estructuran según las necesidades del negocio, la complejidad del flujo de trabajo, el nivel de cobertura y el volumen operativo involucrado.',
    pricingHowTitle: 'Cómo funcionan los precios',
    pricingHowBody: 'El precio depende del alcance del servicio, la profundidad de coordinación, las horas de soporte, el ritmo de comunicación y los requisitos de reportes que su equipo espera en las operaciones diarias.',
    pricingEngagementTitle: 'Opciones de contratación',
    pricingOptionOngoingTitle: 'Soporte continuo',
    pricingOptionOngoingBody: 'Para equipos que requieren continuidad operativa constante en el día a día.',
    pricingOptionSharedTitle: 'Cobertura de soporte compartida',
    pricingOptionSharedBody: 'Para organizaciones que equilibran múltiples flujos de trabajo con prioridades flexibles.',
    pricingOptionProjectTitle: 'Soporte por proyecto',
    pricingOptionProjectBody: 'Para ejecuciones de corto plazo con alcance, cronograma y entregables definidos.',
    pricingFactorsTitle: 'Qué influye en el precio',
    pricingFactorsBody: 'El precio final está influenciado por la complejidad del flujo de trabajo, el volumen del negocio, las horas de soporte requeridas, los requisitos de comunicación y cualquier requisito de sistema o proceso involucrado en la entrega diaria.',
    pricingTailoredTitle: 'Solicite un alcance personalizado',
    pricingTailoredBody: 'Cuéntenos lo que necesita su equipo y prepararemos un alcance de consulta alineado con sus objetivos operativos.',
    pricingTailoredPrimaryCta: 'Solicitar una consulta',
    pricingTailoredSecondaryCta: 'Describa sus necesidades',
    contactHeroTitle: 'Contacte a Gabriel Services',
    contactHeroLead: 'Comuníquese con nuestro equipo para soporte, incorporación, conversaciones de proyectos o consultas de alianza.',
    contactReachTitle: 'Cómo contactarnos',
    contactReachBody: 'Este canal de contacto está diseñado para empresas que necesitan soporte operativo, guía de incorporación de servicios o conversaciones de alianza con Gabriel Services.',
    contactTellTitle: 'Cuéntenos qué necesita',
    contactTellBody: 'Comparta sus flujos actuales, prioridades y necesidades de respuesta esperadas para que podamos dirigir su solicitud con precisión.',
    contactNextTitle: 'Qué sucede después',
    contactNextBody: 'Nuestro equipo revisa los envíos, confirma detalles de alcance cuando es necesario y da seguimiento con los siguientes pasos recomendados y el flujo esperado de incorporación.',
    contact: 'Contacto',
    careers: 'Carreras',
    learning: 'Aprendizaje',
    learningIntro1: 'Explore ideas prácticas y guías centradas en las operaciones diarias del negocio, la consistencia del soporte al cliente, la coordinación logística y los flujos de trabajo administrativos.',
    learningIntro2: 'Esta sección está diseñada para ayudar a los equipos a mantenerse alineados, mejorar la calidad de ejecución y construir sistemas confiables que respalden un crecimiento sostenible.',
    brandSubtitle: 'Tercerización que entrega',
    editorialTheme: 'Corte estilo revista',
    homeHeroTitle: 'Servicios profesionales para logística, TI y operaciones de atención al cliente.',
    homeHeroLead: 'Amplíe su operación con equipos expertos, niveles de servicio medibles y una ejecución precisa en logística, TI y operaciones de atención al cliente.',
    homeHeroPrimaryCta: 'Programar consulta',
    homeHeroSecondaryCta: 'Explorar servicios',
    homeHeroSupportText: 'Equipos orientados a la ejecución, alineados con sus flujos de trabajo diarios, su ritmo de comunicación y resultados medibles.',
    homeOpsTitle: 'Soporte operativo para empresas modernas',
    homeOpsBody1: 'Gabriel Services es un socio de soporte profesional para organizaciones que necesitan una ejecución confiable en logística, coordinación administrativa, operaciones de atención al cliente y solicitudes de TI.',
    homeOpsBody2: 'Brindamos cobertura estructurada, comunicación clara, seguimiento medible y disciplina de procesos que mantiene las operaciones en movimiento sin interrupciones.',
    homeOpsBody3: 'Nuestros equipos se integran con los sistemas y ritmos existentes, creando una capa operativa práctica que ayuda a los líderes a reducir fricción, mejorar la calidad de respuesta y mantenerse enfocados en las prioridades de crecimiento.',
    homeServiceAreasTitle: 'Áreas de servicio diseñadas para la ejecución diaria',
    homeCardLogisticsTitle: 'Operaciones logísticas',
    homeCardLogisticsBody: 'Coordinación de despacho, seguimiento de movimientos y apoyo al flujo de trabajo de entregas con actualizaciones confiables.',
    homeCardAdminTitle: 'Back office administrativo',
    homeCardAdminBody: 'Documentación, programación, gestión de datos y administración de procesos para mantener organizados los sistemas del negocio.',
    homeCardCustomerTitle: 'Operaciones de atención al cliente',
    homeCardCustomerBody: 'Comunicación con clientes, gestión de incidencias y apoyo de continuidad diseñados para ofrecer experiencias de servicio ágiles y consistentes.',
    homeCardItTitle: 'Soporte de TI',
    homeCardItBody: 'Clasificación de solicitudes técnicas, coordinación de resolución de problemas y soporte práctico para las plataformas del día a día.',
    homeWhyTitle: 'Por qué las empresas trabajan con Gabriel Services',
    homeWhyBody: 'Las empresas eligen Gabriel Services por su confiabilidad bajo la presión diaria, una comunicación clara y responsable, una estructura que reduce la desviación operativa y un soporte adaptable que escala según cambian las prioridades.',
    homeStartTitle: 'Comience con el soporte que necesita',
    homeStartBody: 'Programe una consulta para mapear sus flujos de trabajo, definir la cobertura del servicio y construir un plan de ejecución adaptado a sus necesidades operativas.',
    homeStartPrimaryCta: 'Solicitar consulta',
    homeStartSecondaryCta: 'Ver opciones de contratación',
    heroTitle: 'Servicios profesionales para logística, TI y operaciones de atención al cliente.',
    heroBody: 'Escale su operación de soporte con equipos expertos.',
    schedule: 'Programar consulta',
    aboutBody: 'En Gabriel Services, entendemos que el éxito empresarial depende de equipos eficientes, comunicación clara y operaciones diarias confiables.',
    aboutBodyP1: 'En Gabriel Services, creemos que una empresa crece con mayor fuerza cuando sus operaciones diarias funcionan con precisión, consistencia y claridad.',
    aboutBodyP2: 'Nuestra trayectoria como antiguos dueños de pequeñas empresas y profesionales de soporte empresarial remoto, combinada con experiencia en servicio al cliente, logística, soporte técnico, administración y operaciones empresariales, nos ha enseñado que los pequeños detalles pueden convertirse rápidamente en problemas costosos cuando no se gestionan de manera consistente.',
    aboutBodyP3: 'Por eso ayudamos a las empresas a mantenerse organizadas, receptivas y operativamente sólidas. Aportamos experiencia práctica, adaptabilidad y una mentalidad centrada en el cliente a los desafíos cotidianos que enfrentan las compañías, brindando un soporte eficiente, consciente de costos y confiable.',
    aboutBodyP4: 'Nuestro propósito es fortalecer las operaciones diarias para que los dueños de negocios puedan enfocarse en planificar, liderar y crecer con mayor confianza.',

    aboutHeroTitle: 'Sobre Gabriel Services',
    aboutHeroLead: 'Gabriel Services ayuda a las empresas a mantenerse organizadas, receptivas y operativamente sólidas mediante soporte práctico en logística, administración, operaciones de atención al cliente y TI.',
    aboutWhoTitle: 'Quiénes somos',
    aboutWhoBody: 'Gabriel Services nació para brindar a las empresas en crecimiento un socio operativo confiable que entiende el ritmo y la presión de la ejecución diaria.',
    aboutBringTitle: 'Qué aportamos a las operaciones diarias',
    aboutBringBody1: 'Nuestro equipo aporta experiencia directa en servicio al cliente, coordinación logística, back office administrativo, clasificación de incidencias de TI y operaciones diarias del negocio.',
    aboutBringBody2: 'Esta base multifuncional nos permite apoyar los flujos de trabajo de extremo a extremo en lugar de tratar cada solicitud como una tarea aislada.',
    aboutSupportTitle: 'Cómo apoyamos a las empresas en crecimiento',
    aboutSupportBody: 'A medida que las empresas escalan, los pequeños detalles sin gestionar pueden convertirse rápidamente en problemas operativos costosos. Reducimos ese riesgo mediante ejecución consistente, comunicación transparente y seguimiento disciplinado en flujos recurrentes.',
    aboutApproachTitle: 'Nuestro enfoque operativo',
    aboutApproachBody: 'Nuestro enfoque se basa en confiabilidad, ritmo constante de comunicación, ejecución práctica y entrega de servicio consciente de costos para que las empresas mantengan el impulso con confianza.',
    aboutApproachPrimaryCta: 'Explorar servicios',
    aboutApproachSecondaryCta: 'Programar una consulta',
    servicesHeroTitle: 'Servicios',
    servicesHeroLead: 'Gabriel Services brinda soporte operativo flexible en logística, back office administrativo, operaciones de atención al cliente y soporte de TI.',
    servicesHeroCta: 'Conversemos sobre su flujo de trabajo',
    servicesCoverageTitle: 'Soporte profesional en funciones clave del negocio',
    servicesMatrixTitle: 'Matriz de servicios',
    servicesMatrixLead: 'Una vista rápida para entender cómo cada línea de servicio respalda las prioridades de ejecución.',
    servicesMatrixAriaLabel: 'Matriz de capacidades de servicio',
    servicesMatrixHeaderFunction: 'Función',
    servicesMatrixHeaderLogistics: 'Logística',
    servicesMatrixHeaderCustomerOps: 'Operaciones de clientes',
    servicesMatrixHeaderAdmin: 'Back Office administrativo',
    servicesMatrixHeaderIt: 'Soporte de TI',
    servicesMatrixRowOperational: 'Soporte operativo',
    servicesMatrixRowCadence: 'Cadencia de seguimiento',
    servicesMatrixRowDocs: 'Documentación',
    servicesMatrixRowCoordination: 'Coordinación',
    servicesMatrixRowClientContinuity: 'Continuidad con clientes',
    servicesMatrixRowDispatch: 'Soporte de despacho',
    servicesMatrixRowScheduling: 'Programación',
    servicesMatrixRowReporting: 'Reportes',
    servicesEngagementTitle: 'Opciones de contratación',
    servicesEngagementOnDemandTitle: 'Bajo demanda',
    servicesEngagementOnDemandBody: 'Ideal para necesidades variables, picos de trabajo y solicitudes de último minuto.',
    servicesEngagementOnDemandItem1: 'Por hora',
    servicesEngagementOnDemandItem2: 'Bloque de 4 horas',
    servicesEngagementOnDemandItem3: 'Bloque de 8 horas',
    servicesEngagementContinuousTitle: 'Cobertura continua',
    servicesEngagementContinuousBody: 'Ideal para tareas recurrentes y continuidad operativa constante.',
    servicesEngagementContinuousItem1: 'Medio tiempo',
    servicesEngagementContinuousItem2: 'Tiempo completo',
    servicesEngagementContinuousItem3: 'Diario',
    servicesEngagementContinuousItem4: 'Semanal',
    servicesEngagementContinuousItem5: 'Mensual',
    servicesEngagementProjectTitle: 'Por proyecto',
    servicesEngagementProjectBody: 'Ideal para alcances definidos y una ejecución enfocada.',
    servicesEngagementProjectItem1: 'Por proyecto',
    servicesEngagementProjectItem2: 'Corto plazo',
    servicesEngagementProjectItem3: 'Por hitos',
    servicesEngagementCta: 'Programar consulta',
    servicesExecutionTitle: 'Cómo apoyamos la ejecución',
    servicesExecutionItem1: 'Soporte estructurado',
    servicesExecutionItem2: 'Comunicación multilingüe',
    servicesExecutionItem3: 'Seguimiento constante',
    servicesExecutionItem4: 'Operaciones prácticas y conscientes de costos',
    servicesExecutionPrimaryCta: 'Solicite soporte',
    servicesExecutionSecondaryCta: 'Ver opciones de contratación',
    name: 'Nombre',
    email: 'Correo electrónico',
    contactNumber: 'Su número de contacto',
    countryCode: 'Código de país',
    phoneNumber: 'Número de teléfono',
    countryCodePlaceholder: 'Seleccione código de país',
    contactTime: 'Horario más conveniente para contactarle',
    message: 'Mensaje',
    send: 'Enviar',
    sent: 'Mensaje recibido. Nos pondremos en contacto pronto.',
    blocked: 'Contenido bloqueado por seguridad. Elimine contenido sospechoso e inténtelo de nuevo.',
    review: 'Mensaje recibido con precaución. Evite fragmentos HTML/JS, a menos que sean necesarios.',
    contactIntro: 'Comuníquese con nuestro equipo para solicitudes de soporte, incorporación o alianzas.',
    learnMore: 'Conozca más',
    serviceLearnMore: 'Definiciones de servicios',
    serviceCardExploreLink: 'Explorar servicio',
    serviceLabel: 'Servicio',
    serviceCarouselToggles: 'Controles del carrusel de servicios',
    serviceShowPrefix: 'Mostrar',
    serviceCardAction: 'Ver detalles del servicio',
    serviceLogisticsTitle: 'Operaciones Logísticas',
    serviceLogisticsBody: 'Flujos de pedidos, soporte de despacho, actualizaciones de envíos y reportes.',
    serviceItTitle: 'Soporte de TI',
    serviceItBody: 'Nivel 1 y nivel 2: incorporación, implementación, solución de problemas, gestión de cuentas, relaciones con clientes y soporte de dispositivos finales.',
    serviceAdminTitle: 'Backoffice Administrativo',
    serviceAdminBody: 'Ingreso de datos, documentación, apoyo de facturación, cuentas por pagar y cobrar, gestión de procesos, agenda y asistencia ejecutiva.',
    serviceCustomerTitle: 'Relaciones con Clientes',
    serviceCustomerBody: 'Soporte omnicanal, retención de clientes y monitoreo de calidad.',
    serviceDefinitionsTitle: 'Definiciones de servicios',
    serviceDefinitionOperationsTitle: 'Operaciones',
    serviceDefinitionOperationsBody: 'Operaciones es el sistema integral de ejecución que diseña, controla y mejora de forma continua cómo las personas, los procesos y la tecnología convierten insumos en resultados consistentes y de alta calidad, entregando un desempeño predecible en costos, riesgo y resultados para el cliente bajo condiciones reales.',
    serviceDefinitionLogisticsTitle: 'Logística',
    serviceDefinitionLogisticsBody: 'Logística es el sistema integral que planifica, ejecuta y optimiza continuamente el transporte, el almacenamiento, el movimiento de inventario y la visibilidad para trasladar artículos a través de una red desde el origen hasta el destino, logrando cumplimiento puntual, preciso y en buen estado mientras gestiona costo total, capacidad, riesgo y experiencia del cliente.',
    serviceDefinitionRemoteVirtualAssistanceTitle: 'Asistencia virtual remota',
    serviceDefinitionRemoteVirtualAssistanceBody: 'La asistencia virtual remota es una capacidad de fuerza laboral remota y bajo demanda que utiliza flujos de trabajo y herramientas digitales estandarizadas para descargar tareas administrativas, de atención al cliente y operativas, mejorando velocidad, precisión, calidad de servicio y eficiencia de costos mediante resultados medibles.',
    serviceDefinitionTechConsultantLevelITitle: 'Consultor técnico nivel I',
    serviceDefinitionTechConsultantLevelIBody: 'Consultor técnico nivel I es un rol de apoyo a la ejecución que realiza tareas técnicas bien definidas para estabilizar sistemas y cumplir hitos del proyecto utilizando guías estándar, midiendo resultados y escalando la complejidad cuando sea necesario, bajo supervisión senior.',
    serviceDefinitionTechConsultantLevelIITitle: 'Consultor técnico nivel II',
    serviceDefinitionTechConsultantLevelIIBody: 'Consultor técnico nivel II es un responsable independiente de la ejecución que traduce las necesidades del cliente en soluciones implementadas, liderando trabajo acotado de principio a fin para mejorar confiabilidad, seguridad y desempeño en costos, mientras coordina partes interesadas y orienta a personal junior.',
    serviceDefinitionRemoteAdministrativeBackOfficeTitle: 'Back office administrativo remoto',
    serviceDefinitionRemoteAdministrativeBackOfficeBody: 'El back office administrativo remoto es una capacidad escalable y externa que estandariza y ejecuta flujos internos clave de administración, documentación, gestión de datos, coordinación, reportes y controles rutinarios, para que la empresa opere con mayor precisión, ciclos más rápidos y menor costo y riesgo.',

    serviceDetailDescriptionTitle: 'Descripción del servicio',
    serviceDetailCoverageTitle: 'Qué cubre este servicio',
    serviceDetailWorkflowsTitle: 'Flujos de trabajo habituales',
    serviceDetailResultsTitle: 'Resultados operativos',
    serviceDetailCollaborationTitle: 'Cómo funciona la colaboración',
    serviceDetailRelatedTitle: 'Servicios relacionados',
    serviceLogisticsDetailTitle: 'Operaciones logísticas',
    serviceLogisticsDetailLead: 'Operaciones logísticas brinda cobertura de ejecución confiable para flujos diarios con alta coordinación. Ayudamos a gestionar comunicación, seguimiento y documentación entre múltiples frentes para mantener la operación organizada, visible y en curso.',
    serviceLogisticsDetailDescriptionBody: 'Este servicio está diseñado para empresas que necesitan coordinación confiable en operaciones logísticas activas. Ayudamos a mantener el flujo de comunicación, mejorar el seguimiento y fortalecer la alineación en las tareas diarias que sostienen la actividad logística.',
    serviceLogisticsCoverage1: 'Coordinación',
    serviceLogisticsCoverage2: 'Despacho',
    serviceLogisticsCoverage3: 'Seguimiento de entregas',
    serviceLogisticsCoverage4: 'Escalación',
    serviceLogisticsCoverage5: 'Comunicaciones',
    serviceLogisticsCoverage6: 'Documentación',
    serviceLogisticsWorkflow1: 'Seguimiento',
    serviceLogisticsWorkflow2: 'Escalación',
    serviceLogisticsWorkflow3: 'Comunicación y seguimiento',
    serviceLogisticsResult1: 'Menos brechas de comunicación',
    serviceLogisticsResult2: 'Mayor visibilidad de entregas',
    serviceLogisticsResult3: 'Seguimiento operativo más consistente',
    serviceLogisticsResult4: 'Ejecución diaria más sólida',
    serviceLogisticsDetailCollaborationBody: 'Comenzamos revisando su flujo de trabajo, prioridades operativas y requisitos de comunicación. Luego, alineamos el trabajo con su proceso para gestionar tareas logísticas con coordinación más clara, mejores actualizaciones y seguimiento más confiable.',
    serviceAdminDetailTitle: 'Back office administrativo',
    serviceAdminDetailLead: 'Back office administrativo brinda cobertura estructurada para tareas administrativas recurrentes que mantienen estable la operación del negocio. Gestionamos documentación, coordinación interna y seguimiento para sostener procesos organizados y consistentes.',
    serviceAdminDetailDescriptionBody: 'Este servicio está diseñado para empresas que requieren cobertura confiable en operaciones administrativas rutinarias. Ayudamos a reducir acumulaciones de tareas, mantener el orden interno y sostener flujos recurrentes con mayor consistencia y claridad.',
    serviceAdminCoverage1: 'Documentación',
    serviceAdminCoverage2: 'Programación',
    serviceAdminCoverage3: 'Reportes',
    serviceAdminCoverage4: 'Seguimiento operativo',
    serviceAdminCoverage5: 'Coordinación interna',
    serviceAdminCoverage6: 'Continuidad administrativa',
    serviceAdminWorkflow1: 'Preparación y organización documental',
    serviceAdminWorkflow2: 'Mantenimiento de registros',
    serviceAdminWorkflow3: 'Gestión de solicitudes internas',
    serviceAdminWorkflow4: 'Agenda y coordinación',
    serviceAdminWorkflow5: 'Seguimiento administrativo recurrente',
    serviceAdminResult1: 'Organización operativa más sólida',
    serviceAdminResult2: 'Menor acumulación administrativa',
    serviceAdminResult3: 'Mejor continuidad interna',
    serviceAdminResult4: 'Ejecución diaria más consistente',
    serviceAdminDetailCollaborationBody: 'Comenzamos revisando su flujo de trabajo, prioridades recurrentes y ritmo de comunicación. Luego alineamos el trabajo con su proceso interno para que las tareas administrativas se registren, organicen y sigan con mayor consistencia y control.',
    serviceCustomerDetailTitle: 'Relación con clientes',
    serviceCustomerDetailLead: 'Relación con clientes brinda soporte operativo para comunicación y seguimiento a lo largo del ciclo de servicio. Ayudamos a mantener respuestas claras, continuidad de casos y coordinación estable en interacciones diarias con clientes.',
    serviceCustomerDetailDescriptionBody: 'Este servicio está diseñado para empresas que necesitan soporte consistente en comunicación y seguimiento de cara al cliente. Ayudamos a mantener continuidad de respuesta, mejorar la coordinación del servicio y fortalecer la visibilidad de las interacciones en curso.',
    serviceCustomerCoverage1: 'Atención al cliente',
    serviceCustomerCoverage2: 'Gestión de incidencias',
    serviceCustomerCoverage3: 'Comunicación de continuidad',
    serviceCustomerCoverage4: 'Comunicación posventa',
    serviceCustomerCoverage5: 'Seguimiento y escalación',
    serviceCustomerWorkflow1: 'Respuesta a solicitudes de clientes',
    serviceCustomerWorkflow2: 'Actualizaciones de estado y casos',
    serviceCustomerWorkflow3: 'Coordinación de seguimiento',
    serviceCustomerResult1: 'Comunicación con clientes más consistente',
    serviceCustomerResult2: 'Experiencia del cliente más sólida',
    serviceCustomerResult3: 'Menos seguimientos omitidos o tardíos',
    serviceCustomerResult4: 'Mejor continuidad en las interacciones con clientes',
    serviceCustomerDetailCollaborationBody: 'Comenzamos revisando su flujo de comunicación, prioridades de respuesta y expectativas de seguimiento. Luego alineamos el trabajo con su proceso para gestionar interacciones con clientes con mayor consistencia, visibilidad y claridad operativa.',
    serviceItDetailTitle: 'Soporte de TI',
    serviceItDetailLead: 'Soporte de TI brinda cobertura confiable para necesidades técnicas internas del día a día. Ayudamos a organizar la recepción de solicitudes, mantener visibilidad de incidencias abiertas y sostener una comunicación clara durante todo el proceso.',
    serviceItDetailDescriptionBody: 'Este servicio está diseñado para empresas que necesitan cobertura estructurada diaria para solicitudes técnicas internas comunes. Ayudamos a mantener organizado el flujo de tickets, sostener la continuidad de comunicación y mejorar el seguimiento para que las operaciones técnicas rutinarias se mantengan estables y bien coordinadas.',
    serviceItCoverage1: 'Mesa de ayuda',
    serviceItCoverage2: 'Gestión de tickets',
    serviceItCoverage3: 'Coordinación y seguimiento de usuarios',
    serviceItCoverage4: 'Resolución de problemas',
    serviceItCoverage5: 'Comunicación',
    serviceItWorkflow1: 'Gestión de tickets y documentación',
    serviceItWorkflow2: 'Triaje',
    serviceItWorkflow3: 'Seguimiento y coordinación de solicitudes',
    serviceItResult1: 'Flujo operativo más confiable',
    serviceItResult2: 'Mayor visibilidad sobre solicitudes abiertas',
    serviceItResult3: 'Seguimiento y coordinación más claros',
    serviceItResult4: 'Menor fricción en la actividad técnica rutinaria',
    serviceItDetailCollaborationBody: 'Comenzamos revisando su flujo de trabajo, prioridades de solicitudes y necesidades de comunicación. Luego alineamos el trabajo con su proceso interno para que las solicitudes técnicas rutinarias se atiendan con seguimiento claro, mayor visibilidad y coordinación consistente.',
    
    careersTitle: 'Carreras',
    careersIntro: 'Únase a nuestro equipo y ayude a clientes PyME a modernizar operaciones de logística, TI y soporte.',
    careersHeroTitle: 'Carreras en Gabriel Services',
    careersHeroLead: 'Únase a un equipo que ayuda a las empresas a fortalecer sus operaciones de logística, TI, administración y atención al cliente mediante una ejecución práctica y confiable.',
    careersWhyTitle: 'Por qué unirse a Gabriel Services',
    careersWhyBody: 'Nuestro trabajo se centra en el soporte operativo de alta responsabilidad. Se espera que cada integrante del equipo se comunique con claridad, ejecute con constancia y entregue soluciones prácticas bajo la presión real del día a día empresarial.',
    careersFormTitle: 'Formulario de solicitud',
    careersFormBody: 'Comparta información clara y relevante para que nuestro equipo de reclutamiento y operaciones pueda evaluar su perfil con precisión.',
    careersSkillsTitle: 'Habilidades, experiencia y trayectoria',
    careersSkillsBody: 'Las personas candidatas pueden incluir experiencia previa, formación académica, certificaciones, habilidades clave, nivel actual de especialización y capacidades lingüísticas relevantes para funciones de soporte operativo.',
    careersNextTitle: 'Qué sucede después de postularte',
    careersNextBody: 'Tras la revisión, las personas preseleccionadas serán contactadas para los siguientes pasos, la alineación con el puesto y la programación de entrevistas según las prioridades actuales de contratación.',
    experience: 'Experiencia',
    education: 'Educación',
    certification: 'Certificación',
    skills: 'Habilidades',
    expertise: 'Nivel actual de experiencia',
    languages: 'Idiomas',
    controls: 'controles',
    add: 'Agregar',
    remove: 'Quitar',
    lockSection: 'Bloquear sección',
    unlockSection: 'Desbloquear sección',
    submitApplication: 'Enviar solicitud',
    selectLevel: 'Seleccione nivel',
    entry: 'Inicial',
    junior: 'Junior',
    mid: 'Intermedio',
    advanced: 'Avanzado',
    expert: 'Experto',
    placeholderExperience: 'Describa su experiencia',
    placeholderEducation: 'Comparta su formación académica',
    placeholderCertification: 'Liste sus certificaciones',
    placeholderSkills: 'Agregue sus habilidades',
    placeholderExpertise: 'Describa su nivel de experiencia',
    placeholderLanguages: 'Indique idioma(s) y nivel',
    placeholderContactNumber: '555 123 4567',
    fabOpenQuickActions: 'Abrir acciones rápidas',
    fabContact: 'Contacto',
    fabCareer: 'Carreras',
    fabChatbot: 'Chatbot',
    chatPanelLabel: 'Panel del chatbot',
    chatClose: 'Cerrar chatbot',
    chatCloseCta: 'Cerrar',
    chatbot: 'Gabo io',
    chatFrameTitle: 'Asistente de chat',
    legalNavigation: 'Navegación legal',
    legalTerms: 'Términos y condiciones',
    legalCookies: 'Consentimiento de cookies',
    legalPrivacy: 'Privacidad y RGPD',
    footerCompany: 'Empresa',
    footerSupport: 'Soporte',
    footerLegal: 'Legal',
    footerSitemap: 'Mapa del sitio',
    footerTerms: 'Términos y Condiciones',
    footerCookies: 'Consentimiento de Cookies',
    footerGdpr: 'Privacidad y RGPD',
    footerCopyright: 'Gabriel Servicios Profesionales para PYMEs',
    opsHeading: 'Marco de entrega integrado',
    opsIntro: 'Un modelo sincronizado que conecta entrega segura, UX adaptativa, gobernanza y observabilidad bajo un solo ritmo operativo.',
    opsLifecycleTitle: 'Ciclo de vida de código inteligente',
    opsLifecycleBody: 'Coordine CI/CD, automatización cloud-native y documentación en lenguaje claro a lo largo de toda la entrega.',
    opsDesignTitle: 'Inteligencia UX/UI adaptativa',
    opsDesignBody: 'Implemente interfaces centradas en las personas con diseño responsivo, accesibilidad y calidad de interacción medible.',
    opsSecurityTitle: 'Orquestación de seguridad y cumplimiento',
    opsSecurityBody: 'Alinee NIST CSF, CISA Cyber Essentials y controles PCI desde identificar hasta recuperar en toda la operación.',
    opsGovernanceTitle: 'Controles de gobernanza web',
    opsGovernanceBody: 'Refuerce la gobernanza con encabezados seguros, estándares de privacidad y configuración de plataforma orientada a políticas.',
    opsAiTitle: 'Integración de AI/ML/LLM',
    opsAiBody: 'Conecte asistentes y modelos pequeños para personalización en tiempo real preservando seguridad y eficiencia de costos.',
    opsDataTitle: 'Bucles de observabilidad y analítica',
    opsDataBody: 'Monitoree Core Web Vitals, salud de servicios y datos de comportamiento para optimizar continuamente UX, resiliencia y resultados.'
  }
};

export const SERVICES = {
  en: [
    {
      key: 'logistics',
      title: 'Logistics Operations',
      body: 'Support for coordination-heavy logistics workflows that require consistency, communication, and follow-through.',
      items: ['Shipment and delivery coordination', 'Dispatch and status follow-up', 'Billing and operational documentation'],
      href: '/services/logistics-operations/'
    },
    {
      key: 'admin',
      title: 'Administrative Backoffice',
      body: 'Remote administrative support that keeps routine business operations organized and moving.',
      items: ['Documentation and records support', 'Scheduling and coordination tasks', 'Reporting and internal follow-up'],
      href: '/services/administrative-backoffice/'
    },
    {
      key: 'customer',
      title: 'Customer Relations',
      body: 'Customer-facing support that helps businesses stay responsive, clear, and professional.',
      items: ['Customer communication support', 'After-sales follow-up', 'Case updates and service continuity'],
      href: '/services/customer-relations/'
    },
    {
      key: 'it',
      title: 'IT Support',
      body: 'Operational IT assistance for routine support needs and internal issue coordination.',
      items: ['Help desk intake', 'Support ticket follow-up', 'User support coordination'],
      href: '/services/it-support/'
    }
  ],
  es: [
    {
      key: 'logistics',
      title: 'Operaciones Logísticas',
      body: 'Soporte para flujos logísticos con alta coordinación que requieren consistencia, comunicación y seguimiento.',
      items: ['Coordinación de envíos y entregas', 'Despacho y seguimiento de estado', 'Facturación y documentación operativa'],
      href: '/services/logistics-operations/'
    },
    {
      key: 'admin',
      title: 'Backoffice Administrativo',
      body: 'Soporte administrativo remoto que mantiene las operaciones rutinarias organizadas y en movimiento.',
      items: ['Soporte documental y de registros', 'Tareas de agenda y coordinación', 'Reportes y seguimiento interno'],
      href: '/services/administrative-backoffice/'
    },
    {
      key: 'customer',
      title: 'Relaciones con Clientes',
      body: 'Soporte de atención al cliente que ayuda a mantener respuestas claras, ágiles y profesionales.',
      items: ['Soporte de comunicación con clientes', 'Seguimiento postventa', 'Actualizaciones de casos y continuidad del servicio'],
      href: '/services/customer-relations/'
    },
    {
      key: 'it',
      title: 'Soporte de TI',
      body: 'Asistencia operativa de TI para necesidades rutinarias y coordinación interna de incidencias.',
      items: ['Recepción de mesa de ayuda', 'Seguimiento de tickets de soporte', 'Coordinación de soporte a usuarios'],
      href: '/services/it-support/'
    }
  ]
};

export const PLANS = {
  en: [
    { name: 'Individual', price: '$3,950/mo', points: ['Email support', 'Business hours', 'Monthly report'] },
    { name: 'Small Business', price: '$4,850/mo', points: ['24/7 support', 'Priority SLA', 'Weekly optimization'] },
    { name: 'Medium Business', price: '$5,950/mo', points: ['Dedicated team', 'Custom integrations', 'Compliance alignment'] }
  ],
  es: [
    { name: 'Individual', price: '$3,950 usd/mes', points: ['Soporte por correo', 'Horario laboral', 'Reporte mensual'] },
    { name: 'Pequeña Empresa', price: '$4,850 usd/mes', points: ['Soporte 24/7', 'SLA prioritario', 'Optimización semanal'] },
    { name: 'Mediana Empresa', price: '$5,950 usd/mes', points: ['Equipo dedicado', 'Integraciones a medida', 'Alineación de cumplimiento'] }
  ]
};

// ================================================================
// Translation maintenance guide (single-script map by page/route)
// ================================================================
export const TRANSLATION_PAGE_MAP = Object.freeze({
  shared: {
    route: '*',
    description: 'Global UI copy reused across pages (nav, footer, common controls).',
    keyPrefixes: ['switchTo', 'footer', 'fab', 'chat', 'pageTitle', 'pageDescription', 'ogLocale'],
    exactKeys: ['home', 'services', 'about', 'pricing', 'contact', 'careers', 'learning', 'brandSubtitle', 'editorialTheme']
  },
  home: {
    route: '/',
    description: 'Homepage editorial sections and CTAs.',
    keyPrefixes: ['homeHero', 'homeOps', 'homeCard', 'homeWhy', 'homeStart', 'homeServiceAreas']
  },
  about: {
    route: '/about/',
    description: 'About page narrative content.',
    keyPrefixes: ['aboutBody', 'aboutHero', 'aboutWho', 'aboutBring', 'aboutSupport', 'aboutApproach']
  },
  services: {
    route: '/services/',
    description: 'Services overview and service definition entries.',
    keyPrefixes: ['service', 'serviceDefinition', 'servicesHero', 'servicesCoverage']
  },
  logistics: {
    route: '/services/logistics-operations/',
    description: 'Logistics page and logistics-specific copy hooks.',
    keyPrefixes: ['serviceLogistics', 'serviceDefinitionLogistics']
  },
  administrativeBackoffice: {
    route: '/services/administrative-backoffice/',
    description: 'Administrative backoffice service page copy hooks.',
    keyPrefixes: ['serviceAdmin', 'serviceDefinitionRemoteAdministrativeBackOffice']
  },
  customerRelations: {
    route: '/services/customer-relations/',
    description: 'Customer relations service page copy hooks.',
    keyPrefixes: ['serviceCustomer']
  },
  itSupport: {
    route: '/services/it-support/',
    description: 'IT support service page copy hooks.',
    keyPrefixes: ['serviceIt', 'serviceDefinitionTechConsultantLevelI', 'serviceDefinitionTechConsultantLevelII']
  },
  pricing: {
    route: '/pricing/',
    description: 'Pricing page labels and plan related copy.',
    keyPrefixes: ['pricing']
  },
  careers: {
    route: '/careers/',
    description: 'Careers form labels, placeholders, and controls.',
    keyPrefixes: ['careers', 'experience', 'education', 'certification', 'skills', 'expertise', 'placeholder', 'selectLevel', 'entry', 'junior', 'mid', 'advanced', 'expert', 'submitApplication', 'lockSection', 'unlockSection', 'controls', 'add', 'remove']
  },
  contact: {
    route: '/contact/',
    description: 'Contact form labels and security status copy.',
    keyPrefixes: ['name', 'email', 'contact', 'countryCode', 'message', 'send', 'sent', 'blocked', 'review', 'contactHero', 'contactReach', 'contactTell', 'contactNext']
  },
  learning: {
    route: '/learning/',
    description: 'Learning and framework explainer copy.',
    keyPrefixes: ['ops', 'learningIntro']
  },
  legal: {
    route: '/legal/*',
    description: 'Legal page links surfaced in UI/footer.',
    keyPrefixes: ['footerTerms', 'footerCookies', 'footerGdpr']
  }
});

function keyMatchesSection(key, section = {}) {
  const prefixes = section.keyPrefixes || [];
  const exactKeys = section.exactKeys || [];

  if (exactKeys.includes(key)) return true;
  return prefixes.some((prefix) => key.startsWith(prefix));
}

export function getTranslationsBySection(language = 'en', sectionName = 'shared') {
  const langPack = DICTIONARY[language] || DICTIONARY.en;
  const section = TRANSLATION_PAGE_MAP[sectionName];
  if (!section) return {};

  return Object.fromEntries(
    Object.entries(langPack).filter(([key]) => keyMatchesSection(key, section))
  );
}
